# Generated by Django 2.2.9 on 2020-04-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerDescription',
        ),
        migrations.DeleteModel(
            name='PartnerInfo',
        ),
    ]
