# Generated by Django 2.2 on 2020-05-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_join_nachricht_verschickt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='join',
            options={'verbose_name': 'Newsletter Abonierte', 'verbose_name_plural': 'Newsletter'},
        ),
        migrations.AlterModelOptions(
            name='treeathloninzahlen',
            options={'verbose_name': 'TreeathlonInZahlen', 'verbose_name_plural': 'Treeathlon in Zahlen Beschreibung'},
        ),
        migrations.AlterModelOptions(
            name='vision',
            options={'verbose_name': 'Vision', 'verbose_name_plural': 'Unser Vision'},
        ),
        migrations.RemoveField(
            model_name='join',
            name='nachricht_verschickt',
        ),
    ]
