# Generated by Django 2.2.9 on 2020-04-23 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
