# Generated by Django 2.2.9 on 2020-04-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_auto_20200423_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='start_date',
        ),
    ]
