# Generated by Django 2.2.9 on 2020-04-23 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_auto_20200423_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='from_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
