# Generated by Django 2.2.9 on 2020-04-23 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_events_from_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='from_date',
        ),
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
