# Generated by Django 2.2 on 2020-05-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0006_auto_20200522_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
