# Generated by Django 2.2 on 2020-05-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0007_events_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='link_text',
            field=models.TextField(default='Facebook Event'),
        ),
    ]
