# Generated by Django 2.2 on 2020-05-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0008_events_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='link_text',
            field=models.TextField(default='Facebook Event', max_length=50),
        ),
    ]
