# Generated by Django 2.2 on 2020-05-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0010_auto_20200524_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='link_text',
            field=models.CharField(default='facebook event', max_length=50),
        ),
    ]
