# Generated by Django 2.2 on 2020-05-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacy',
            options={'verbose_name': 'Privacy Inhalt', 'verbose_name_plural': 'Privacys Inhalt'},
        ),
    ]
