# Generated by Django 2.2.9 on 2020-05-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spenden_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnahme',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstellt am'),
        ),
    ]
