# Generated by Django 2.2 on 2020-05-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spenden_app', '0002_teilnahme_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendeDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=40)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
