# Generated by Django 2.2 on 2020-05-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spenden_app', '0003_spendedescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teilnahme',
            options={'verbose_name': 'TeilnehmerIn', 'verbose_name_plural': 'Teilnahmers'},
        ),
        migrations.AlterField(
            model_name='spendedescription',
            name='title',
            field=models.CharField(default='default', max_length=70),
        ),
    ]
