# Generated by Django 2.2.9 on 2020-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerinfo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerinfo',
            name='name_partner',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
