# Generated by Django 2.2.9 on 2020-04-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_auto_20200424_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactadressen',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
