# Generated by Django 2.2.9 on 2020-04-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=40)),
                ('cover', models.ImageField(blank=True, max_length=150, null=True, upload_to='images/')),
                ('our_description', models.TextField(blank=True, null=True)),
                ('self_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=40)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
