# Generated by Django 2.2 on 2020-05-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'content', 'verbose_name_plural': 'Unser Kontakt Info auf der Fusszeile unten'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Eine Person', 'verbose_name_plural': 'Unser Team auf der About Seite'},
        ),
        migrations.AlterModelOptions(
            name='teamdescription',
            options={'verbose_name': 'Contact Info', 'verbose_name_plural': 'Unser About Beschreibung auf der About Seite oben'},
        ),
    ]
